/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PersonManager;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Address;
import model.PersonProfile;
import model.PersonProfileDirectory;
/**
 *
 * @author jaswa
 */
public class ViewPersonJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PersonProfileDirectory persondirectory;
    private PersonProfile personprofile;
    /**
     * Creates new form ViewPersonJPanel
     */
    public ViewPersonJPanel(JPanel userProcessContainer,PersonProfileDirectory persondirectory, PersonProfile personprofile  ) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.personprofile=personprofile;
        
        refreshTextFields();
        setViewMode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        txtWorkPhoneno = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblWorkZipCode = new javax.swing.JLabel();
        txtHomeState = new javax.swing.JTextField();
        txtWorkZipCode = new javax.swing.JTextField();
        lblHomeStreetAdd = new javax.swing.JLabel();
        lblWorkPhoneno = new javax.swing.JLabel();
        txtHomeStreetAdd = new javax.swing.JTextField();
        lblHomeUnitNo = new javax.swing.JLabel();
        txtHomeUnitNo = new javax.swing.JTextField();
        lblHomeCity = new javax.swing.JLabel();
        txtHomeCity = new javax.swing.JTextField();
        lblHomeState = new javax.swing.JLabel();
        txtWorkState = new javax.swing.JTextField();
        lblWorkStreetAdd = new javax.swing.JLabel();
        txtWorkStreetAdd = new javax.swing.JTextField();
        lblHomeAdd = new javax.swing.JLabel();
        lblWorkUnitNo = new javax.swing.JLabel();
        lblWorkAddress = new javax.swing.JLabel();
        txtWorkUnitNo = new javax.swing.JTextField();
        lblWorkCity = new javax.swing.JLabel();
        lblfirstname = new javax.swing.JLabel();
        txtWorkCity = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        lblWorkState = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtHomePhoneno = new javax.swing.JTextField();
        lblHomeZipCode = new javax.swing.JLabel();
        lblssn = new javax.swing.JLabel();
        txtHomeZipCode = new javax.swing.JTextField();
        BtnSave = new javax.swing.JButton();
        txtSSN = new javax.swing.JTextField();
        lblHomePhoneno = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 245, 220));

        btnBack.setBackground(new java.awt.Color(173, 216, 230));
        btnBack.setText("<<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Times", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View Person Profile");

        lblAge.setText("Age");

        lblWorkZipCode.setText("ZipCode");

        lblHomeStreetAdd.setText("Street Address");

        lblWorkPhoneno.setText("Phone Number");

        lblHomeUnitNo.setText("Unit Number");

        lblHomeCity.setText("City");

        lblHomeState.setText("State");

        lblWorkStreetAdd.setText("Street Address");

        txtWorkStreetAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWorkStreetAddActionPerformed(evt);
            }
        });

        lblHomeAdd.setForeground(new java.awt.Color(0, 0, 198));
        lblHomeAdd.setText("Home Address");

        lblWorkUnitNo.setText("Unit Number");

        lblWorkAddress.setForeground(new java.awt.Color(0, 0, 128));
        lblWorkAddress.setText("Work Address");

        lblWorkCity.setText("City");

        lblfirstname.setText("FirstName");

        lblWorkState.setText("State");

        lblLastName.setText("LastName");

        lblHomeZipCode.setText("Zip Code");

        lblssn.setText("Social Security Number");

        BtnSave.setText("Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        lblHomePhoneno.setText("Phone Number");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(18, 18, 18)
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(BtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(btnUpdate))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtSSN)
                                                .addGap(53, 53, 53))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblssn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(48, 48, 48)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(lblHomeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(409, 409, 409)
                .addComponent(lblWorkAddress)
                .addGap(151, 151, 151))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtHomeZipCode)
                                .addComponent(lblHomeZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblHomePhoneno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtHomePhoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtWorkZipCode)
                                .addComponent(lblWorkZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblWorkPhoneno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtWorkPhoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtHomeCity)
                                        .addComponent(lblHomeCity, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(53, 53, 53)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblHomeState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtHomeState, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblHomeStreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHomeStreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(53, 53, 53)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHomeUnitNo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblHomeUnitNo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(182, 182, 182)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtWorkCity)
                                        .addComponent(lblWorkCity, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(53, 53, 53)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblWorkState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtWorkState, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblWorkStreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtWorkStreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(53, 53, 53)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtWorkUnitNo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblWorkUnitNo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnSave, btnUpdate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblfirstname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblssn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHomeAdd)
                    .addComponent(lblWorkAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSave)
                    .addComponent(btnUpdate))
                .addGap(57, 57, 57))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(269, 269, 269)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblHomeStreetAdd)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtHomeStreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblHomeUnitNo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtHomeUnitNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblHomeCity)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtHomeCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblHomeState)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtHomeState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblWorkStreetAdd)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtWorkStreetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblWorkUnitNo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtWorkUnitNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblWorkCity)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtWorkCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblWorkState)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtWorkState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblHomeZipCode)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtHomeZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblHomePhoneno)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtHomePhoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblWorkZipCode)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtWorkZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblWorkPhoneno)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtWorkPhoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(131, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
    
    Component[] panelStack = userProcessContainer.getComponents();
    JPanel lastpanel = (JPanel) panelStack[panelStack.length-1];
    ListPersonJPanel manageaccountjpanel = (ListPersonJPanel) lastpanel;
    manageaccountjpanel.populateTable();
    
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtWorkStreetAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWorkStreetAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWorkStreetAddActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        
        int age;
        long homeunitno;
        float homezipcode;
        double homephonenumber;
        long workunitno;
        float workzipcode;
        double workphoneno;
        
        Address homeAddress = new Address();
        Address workAddress = new Address();
        
        String firstname = txtFirstName.getText();
        String lastname = txtLastName.getText();
        String ssn = txtSSN.getText();
        String homeStreetAdd = txtHomeStreetAdd.getText();
        String homecity = txtHomeCity.getText();
        String homestate = txtHomeState.getText();
        String workStreetAddress = txtWorkStreetAdd.getText();
        String workcity = txtWorkCity.getText();
        String workstate = txtWorkState.getText();
        
        if(firstname.isBlank() || lastname.isBlank() || ssn.isBlank() || homeStreetAdd.isBlank()|| homecity.isBlank()|| homestate.isBlank()||workStreetAddress.isBlank()|| workcity.isBlank() || workstate.isBlank() )
        {
            JOptionPane.showMessageDialog(this, "All fields are mandatory", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            age = Integer.parseInt(txtAge.getText());
            homeunitno =  Long.parseLong(txtHomeUnitNo.getText());
            homezipcode = Float.parseFloat(txtHomeZipCode.getText());
            homephonenumber = Double.parseDouble(txtHomePhoneno.getText());
            workunitno = Long.parseLong(txtWorkUnitNo.getText());
            workzipcode = Float.parseFloat(txtWorkZipCode.getText());
            workphoneno = Double.parseDouble(txtWorkPhoneno.getText());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please Enter a Value", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        personprofile.setFirstname(firstname);
        personprofile.setLastname(lastname);
        personprofile.setSsn(ssn);
        personprofile.setAge(age);
        homeAddress.setStreetaddress(homeStreetAdd);
        homeAddress.setUnitnumber(homeunitno);
        homeAddress.setCity(homecity);
        homeAddress.setState(homestate);
        homeAddress.setZipcode(homezipcode);
        homeAddress.setPhonenumber(homephonenumber);
        
        personprofile.setHomeaddress(homeAddress);
        
        workAddress.setStreetaddress(workStreetAddress);
        workAddress.setUnitnumber(workunitno);
        workAddress.setCity(workcity);
        workAddress.setState(workstate);
        workAddress.setZipcode(workzipcode);
        workAddress.setPhonenumber(workphoneno);
        
        personprofile.setWorkaddress(workAddress);
        
        JOptionPane.showMessageDialog(this, "Account Succesfully Updated", "Information", JOptionPane.INFORMATION_MESSAGE);
        
        setViewMode();
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        setEditMode();
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblHomeAdd;
    private javax.swing.JLabel lblHomeCity;
    private javax.swing.JLabel lblHomePhoneno;
    private javax.swing.JLabel lblHomeState;
    private javax.swing.JLabel lblHomeStreetAdd;
    private javax.swing.JLabel lblHomeUnitNo;
    private javax.swing.JLabel lblHomeZipCode;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWorkAddress;
    private javax.swing.JLabel lblWorkCity;
    private javax.swing.JLabel lblWorkPhoneno;
    private javax.swing.JLabel lblWorkState;
    private javax.swing.JLabel lblWorkStreetAdd;
    private javax.swing.JLabel lblWorkUnitNo;
    private javax.swing.JLabel lblWorkZipCode;
    private javax.swing.JLabel lblfirstname;
    private javax.swing.JLabel lblssn;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHomeCity;
    private javax.swing.JTextField txtHomePhoneno;
    private javax.swing.JTextField txtHomeState;
    private javax.swing.JTextField txtHomeStreetAdd;
    private javax.swing.JTextField txtHomeUnitNo;
    private javax.swing.JTextField txtHomeZipCode;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtWorkCity;
    private javax.swing.JTextField txtWorkPhoneno;
    private javax.swing.JTextField txtWorkState;
    private javax.swing.JTextField txtWorkStreetAdd;
    private javax.swing.JTextField txtWorkUnitNo;
    private javax.swing.JTextField txtWorkZipCode;
    // End of variables declaration//GEN-END:variables

    private void refreshTextFields() {
      txtFirstName.setText(personprofile.getFirstname());
      txtLastName.setText(personprofile.getLastname());
      txtSSN.setText(personprofile.getSsn());
      txtHomeStreetAdd.setText(personprofile.getHomeaddress().getStreetaddress());
      txtHomeCity.setText(personprofile.getHomeaddress().getCity());
      txtHomeState.setText(personprofile.getHomeaddress().getState());
      txtWorkStreetAdd.setText(personprofile.getWorkaddress().getStreetaddress());
      txtWorkCity.setText(personprofile.getWorkaddress().getCity());
      txtWorkState.setText(personprofile.getWorkaddress().getState());
      txtAge.setText(String.valueOf(personprofile.getAge()));
    txtHomeUnitNo.setText(String.valueOf(personprofile.getHomeaddress().getUnitnumber()));
      txtHomeZipCode.setText(String.valueOf(personprofile.getHomeaddress().getZipcode()));
      txtHomePhoneno.setText(String.valueOf(personprofile.getHomeaddress().getPhonenumber()));
      txtWorkUnitNo.setText(String.valueOf(personprofile.getWorkaddress().getUnitnumber()));
      txtWorkZipCode.setText(String.valueOf(personprofile.getWorkaddress().getZipcode()));
      txtWorkPhoneno.setText(String.valueOf(personprofile.getWorkaddress().getPhonenumber()));
      
      
      
    }

    private void setViewMode() {
        txtFirstName.setEnabled(false);
      txtLastName.setEnabled(false);
      txtSSN.setEnabled(false);
      txtHomeStreetAdd.setEnabled(false);
      txtHomeCity.setEnabled(false);
      txtHomeState.setEnabled(false);
      txtWorkStreetAdd.setEnabled(false);
      txtWorkCity.setEnabled(false);
      txtWorkState.setEnabled(false);
      txtAge.setEnabled(false);
      txtHomeUnitNo.setEnabled(false);
      txtHomeZipCode.setEnabled(false);
      txtHomePhoneno.setEnabled(false);
      txtWorkUnitNo.setEnabled(false);
      txtWorkZipCode.setEnabled(false);
      txtWorkPhoneno.setEnabled(false);
      
      
      BtnSave.setEnabled(false);
      btnUpdate.setEnabled(true);
    }
    
    private void setEditMode()
    {
         txtFirstName.setEnabled(true);
      txtLastName.setEnabled(true);
      txtSSN.setEnabled(true);
      txtHomeStreetAdd.setEnabled(true);
      txtHomeCity.setEnabled(true);
      txtHomeState.setEnabled(true);
      txtWorkStreetAdd.setEnabled(true);
      txtWorkCity.setEnabled(true);
      txtWorkState.setEnabled(true);
      txtAge.setEnabled(true);
      txtHomeUnitNo.setEnabled(true);
      txtHomeZipCode.setEnabled(true);
      txtHomePhoneno.setEnabled(true);
      txtWorkUnitNo.setEnabled(true);
      txtWorkZipCode.setEnabled(true);
      txtWorkPhoneno.setEnabled(true);
      
      BtnSave.setEnabled(true);
      btnUpdate.setEnabled(false);
    }
}
