/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.personprofile;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.PersonDirectory;
import model.Person;
/**
 *
 * @author jaswa
 */
public class ListPersonProfileJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    PersonDirectory personDirectory;
    
    
    /**
     * Creates new form ListPersonProfileJPanel
     */
    public ListPersonProfileJPanel(JPanel container,PersonDirectory directory) {
        initComponents();
        this.userProcessContainer = container;
        this.personDirectory = directory;
        populateTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PersonProfilelbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersons = new javax.swing.JTable();
        deletebtn = new javax.swing.JButton();

        PersonProfilelbl.setBackground(new java.awt.Color(204, 255, 255));
        PersonProfilelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonProfilelbl.setText("Person Profile List ");

        tblPersons.setBackground(new java.awt.Color(153, 153, 255));
        tblPersons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "first name", "last name", "City (Home Address)", "Zip Code (Home Address)", "City ( Work Address)", "Zip Code ( Work Address)"
            }
        ));
        jScrollPane1.setViewportView(tblPersons);

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PersonProfilelbl, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deletebtn)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PersonProfilelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deletebtn)
                .addContainerGap(11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPersons.getSelectedRow();
    
    if (selectedRow >= 0) {
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the selected Person?", "Warning", JOptionPane.WARNING_MESSAGE);
        
        if (dialogResult == JOptionPane.YES_OPTION) {
            Person selectedPerson = (Person) personDirectory.getPersons().get(selectedRow);
            personDirectory.deletePerson(selectedPerson);
            populateTable();
        }
    } else {
        JOptionPane.showMessageDialog(null, "Please select a person from the list.", "Warning", JOptionPane.WARNING_MESSAGE);
    }
       
    }//GEN-LAST:event_deletebtnActionPerformed

    
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblPersons.getModel();
        model.setRowCount(0);
        
        for (Person p : personDirectory.getPersons()) {
            
            Object[] row = new Object[6];
            row[0] = p.getFirstName();
            row[1] = p.getLastName();
            row[2] = p.getHomeCity();
            row[3] = p.getHomeZipCode();
            row[4]=p.getWorkCity();
            row[5]=p.getWorkZipCode(); 
            
            model.addRow(row);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PersonProfilelbl;
    private javax.swing.JButton deletebtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPersons;
    // End of variables declaration//GEN-END:variables
}
