/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import UI.PersonManager.PersonMngWorkAreaJPanel;
import java.awt.CardLayout;
import model.Address;
import model.PersonProfile;
import model.PersonProfileDirectory;

/**
 *
 * @author jaswa
 */
public class MainJFrame extends javax.swing.JFrame {

   private PersonProfileDirectory persondirectory;
    
    public MainJFrame() {
        initComponents();
        this.persondirectory = new PersonProfileDirectory();
        generateDemoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        btnInitiatePerson = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftPanel.setBackground(new java.awt.Color(245, 245, 220));

        btnInitiatePerson.setBackground(new java.awt.Color(52, 152, 219));
        btnInitiatePerson.setForeground(new java.awt.Color(255, 255, 255));
        btnInitiatePerson.setText("Initiate Person Directory");
        btnInitiatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInitiatePersonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInitiatePerson)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(btnInitiatePerson)
                .addContainerGap(319, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(leftPanel);

        userProcessContainer.setBackground(new java.awt.Color(192, 192, 192));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1098, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInitiatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInitiatePersonActionPerformed
        PersonMngWorkAreaJPanel panel  = new PersonMngWorkAreaJPanel(userProcessContainer, persondirectory);
        userProcessContainer.add("PersonMngWorkAreaJPanel",panel);
        
        CardLayout layout  = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnInitiatePersonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInitiatePerson;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

    private void generateDemoData() {
        
        Address homeAddress = new Address();
        Address workAddress = new Address();
        
        PersonProfile  newperson = persondirectory.addPerson();
        newperson.setFirstname("Abhinav");
        newperson.setLastname("Chinta");
        newperson.setSsn("34809fdfd");
        newperson.setAge(23);
        homeAddress.setStreetaddress("Northampton");
        homeAddress.setUnitnumber(123);
        homeAddress.setCity("Boston");
        homeAddress.setState("Mass");
        homeAddress.setZipcode(123);
        homeAddress.setPhonenumber(9652528);
        
        newperson.setHomeaddress(homeAddress);
        
        workAddress.setStreetaddress("Thronton");
        workAddress.setUnitnumber(35);
        workAddress.setCity("Boston");
        workAddress.setState("Mass");
        workAddress.setZipcode(1234);
        workAddress.setPhonenumber(4567);
        
        newperson.setWorkaddress(workAddress);
        
        
        
        
       
        
        PersonProfile  another1newperson = persondirectory.addPerson();
        another1newperson.setFirstname("Pranit");
        another1newperson.setLastname("Mathyam");
        another1newperson.setSsn("eferg32434");
        another1newperson.setAge(24);
         homeAddress.setStreetaddress("North");
        homeAddress.setUnitnumber(124);
        homeAddress.setCity("Boston");
        homeAddress.setState("Mass");
        homeAddress.setZipcode(124);
        homeAddress.setPhonenumber(932542);
        
        another1newperson.setHomeaddress(homeAddress);
        
        workAddress.setStreetaddress("Thronto");
        workAddress.setUnitnumber(37);
        workAddress.setCity("Boston");
        workAddress.setState("Mass");
        workAddress.setZipcode(123);
        workAddress.setPhonenumber(63532);
        
        another1newperson.setWorkaddress(workAddress);
        
        
        
        
        
        
        PersonProfile  another2newperson = persondirectory.addPerson();
        another2newperson.setFirstname("Nikhil");
        another2newperson.setLastname("Godalla");
        another2newperson.setSsn("eferg32434");
        another2newperson.setAge(26);
         homeAddress.setStreetaddress("Thornton");
        homeAddress.setUnitnumber(116);
        homeAddress.setCity("Boston");
        homeAddress.setState("Mass");
        homeAddress.setZipcode(32676);
        homeAddress.setPhonenumber(672542);
        
        another2newperson.setHomeaddress(homeAddress);
        
        workAddress.setStreetaddress("Thronto");
        workAddress.setUnitnumber(37);
        workAddress.setCity("Boston");
        workAddress.setState("Mass");
        workAddress.setZipcode(123);
        workAddress.setPhonenumber(84533);
        
        another2newperson.setWorkaddress(workAddress);
        
        
        
        
        
        
        
        
        PersonProfile  another3newperson = persondirectory.addPerson();
        another3newperson.setFirstname("Mark");
        another3newperson.setLastname("James");
        another3newperson.setSsn("eferg62464");
        another3newperson.setAge(19);
         homeAddress.setStreetaddress("South");
        homeAddress.setUnitnumber(654);
        homeAddress.setCity("Boston");
        homeAddress.setState("Mass");
        homeAddress.setZipcode(653);
        homeAddress.setPhonenumber(562542);
        
        another3newperson.setHomeaddress(homeAddress);
        
        workAddress.setStreetaddress("washington st");
        workAddress.setUnitnumber(76);
        workAddress.setCity("Boston");
        workAddress.setState("Mass");
        workAddress.setZipcode(456);
        workAddress.setPhonenumber(44782);
        
        another3newperson.setWorkaddress(workAddress);
        
        
      
        
        PersonProfile  another4newperson = persondirectory.addPerson();
        another4newperson.setFirstname("Sofia");
        another4newperson.setLastname("James");
        another4newperson.setSsn("eferg55646");
        another4newperson.setAge(22);
         homeAddress.setStreetaddress("LongWood");
        homeAddress.setUnitnumber(223);
        homeAddress.setCity("Boston");
        homeAddress.setState("Mass");
        homeAddress.setZipcode(678);
        homeAddress.setPhonenumber(876543);
        
        another4newperson.setHomeaddress(homeAddress);
        
        workAddress.setStreetaddress("roxboury");
        workAddress.setUnitnumber(43);
        workAddress.setCity("Boston");
        workAddress.setState("Mass");
        workAddress.setZipcode(223);
        workAddress.setPhonenumber(556532);
        
        another4newperson.setWorkaddress(workAddress);
        
        
        
     
        
        
}
}
