/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import model.Person;
import model.PersonDirectory;
import ui.personprofile.CreatePersonProfileJPanel  ;
import ui.personprofile.ListPersonProfileJPanel;
/**
 *
 * @author jaswa
 */
public class MainJFrame extends javax.swing.JFrame {
    
        private PersonDirectory personDirectory;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.personDirectory = new PersonDirectory();
        generateDemoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftjpanel = new javax.swing.JPanel();
        personprofilelbl = new javax.swing.JLabel();
        addpersonbtn = new javax.swing.JButton();
        listpersonlbl = new javax.swing.JButton();
        searchforpersonlbl = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftjpanel.setBackground(new java.awt.Color(102, 102, 255));

        personprofilelbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        personprofilelbl.setText("Person Profile");

        addpersonbtn.setText("Add Perosn ");
        addpersonbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpersonbtnActionPerformed(evt);
            }
        });

        listpersonlbl.setText("List Person");
        listpersonlbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listpersonlblActionPerformed(evt);
            }
        });

        searchforpersonlbl.setText("Search for Person");
        searchforpersonlbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchforpersonlblActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftjpanelLayout = new javax.swing.GroupLayout(leftjpanel);
        leftjpanel.setLayout(leftjpanelLayout);
        leftjpanelLayout.setHorizontalGroup(
            leftjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftjpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftjpanelLayout.createSequentialGroup()
                        .addComponent(personprofilelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(leftjpanelLayout.createSequentialGroup()
                        .addGroup(leftjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addpersonbtn)
                            .addComponent(listpersonlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchforpersonlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        leftjpanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addpersonbtn, listpersonlbl, searchforpersonlbl});

        leftjpanelLayout.setVerticalGroup(
            leftjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftjpanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(personprofilelbl)
                .addGap(38, 38, 38)
                .addComponent(addpersonbtn)
                .addGap(18, 18, 18)
                .addComponent(listpersonlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchforpersonlbl)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(leftjpanel);

        userProcessContainer.setBackground(new java.awt.Color(102, 255, 0));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listpersonlblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listpersonlblActionPerformed
        // TODO add your handling code here:
        ListPersonProfileJPanel panel = new ListPersonProfileJPanel(userProcessContainer, personDirectory);
        userProcessContainer.add("ListPersonProfileJPanel",panel);
        

        CardLayout layout  = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_listpersonlblActionPerformed

    private void searchforpersonlblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchforpersonlblActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_searchforpersonlblActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void addpersonbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpersonbtnActionPerformed
        // TODO add your handling code here:
        CreatePersonProfileJPanel panel = new CreatePersonProfileJPanel(userProcessContainer, personDirectory);
        userProcessContainer.add("CreatePersonProfileJPanel",panel);
        

        CardLayout layout  = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_addpersonbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addpersonbtn;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel leftjpanel;
    private javax.swing.JButton listpersonlbl;
    private javax.swing.JLabel personprofilelbl;
    private javax.swing.JButton searchforpersonlbl;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

    private void generateDemoData() {
        
        
        // Create and add the first person
    Person person1 = new Person();
    person1.setFirstName("Jaswanth");
    person1.setLastName("Gurujala");
    person1.setHomeCity("Boston");
    person1.setHomeZipCode("02119");
    person1.setWorkCity("Boston");
    person1.setWorkZipCode("02119");
    personDirectory.addPerson(person1);

    // Create and add the second person
    Person person2 = new Person();
    person2.setFirstName("Emily");
    person2.setLastName("Smith");
    person2.setHomeCity("Cambridge");
    person2.setHomeZipCode("02138");
    person2.setWorkCity("Cambridge");
    person2.setWorkZipCode("02138");
    personDirectory.addPerson(person2);

    // Create and add the third person
    Person person3 = new Person();
    person3.setFirstName("Michael");
    person3.setLastName("Johnson");
    person3.setHomeCity("Somerville");
    person3.setHomeZipCode("02143");
    person3.setWorkCity("Somerville");
    person3.setWorkZipCode("02143");
    personDirectory.addPerson(person3);

    // Create and add the fourth person
    Person person4 = new Person();
    person4.setFirstName("Sarah");
    person4.setLastName("Williams");
    person4.setHomeCity("Newton");
    person4.setHomeZipCode("02460");
    person4.setWorkCity("Newton");
    person4.setWorkZipCode("02460");
    personDirectory.addPerson(person4);

    // Create and add the fifth person
    Person person5 = new Person();
    person5.setFirstName("David");
    person5.setLastName("Brown");
    person5.setHomeCity("Brookline");
    person5.setHomeZipCode("02445");
    person5.setWorkCity("Brookline");
    person5.setWorkZipCode("02445");
    personDirectory.addPerson(person5);
        
      
    
}
    
    
}
